version: 1.0.{build}
configuration: LIVE
cache:
    - packages -> **\packages.config
before_build: nuget restore
build:
  publish_wap: true
deploy:
  provider: Environment
  name: Game
  on:
    branch: main